<?php use Snowdog\Academy\Model\Book;

require_once(__DIR__ . '/../../common/header.phtml'); ?>


<section id="book-list" class="padded">
    <h3>Borrowed Book list</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Author</th>
                <th>ISBN</th>
                <th>Borrowed</th>
                <th>Borrowed At</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            if(isset($_POST['submit'])){
                $day = $_POST['day'];
                foreach ($this->getFilterBooks($day) as $book): 
            ?>
            <tr>
                <td><?= $book->getId()?></td>
                <td><?= $book->getTitle()?></td>
                <td><?= $book->getAuthor()?></td>
                <td><?= $book->getIsbn()?></td>
                <td><?= $book->isBorrowed() ? 'Yes' : 'No' ?></td>
                <td><?= $book->borrowedAt()?></td>
            </tr>
            <?php endforeach; }?>
        </tbody>
    </table>
</section>

<?php require_once(__DIR__ . '/../../common/footer.phtml'); ?>

