<?php 

require_once(__DIR__ . '/../../common/header.phtml');

//enctype = "multipart/form-data"

?>

<section id="new-book-form" class="padded">
    <form class="form-horizontal" method="POST" action = "/admin/import_books" enctype = "multipart/form-data">
        <div class="form-group">
            <label for="file-name" class="col-sm-1 control-label">Choose file:</label>
            <div class="col-sm-10">
                <input type="file" id="file-name" name="file" class="form-control" accept=".csv" required/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-2">
                <button type="submit" name="submit" class="btn btn-primary">Import</button>
            </div>
        </div>
    </form>
</section>

<?php require_once(__DIR__ . '/../../common/footer.phtml'); ?>
