<?php use Snowdog\Academy\Model\Book;

require_once(__DIR__ . '/../../common/header.phtml'); ?>

<section id="add" class="padded">
    <a href="/admin/new_book" class="btn btn-primary">Add new book</a>
</section>
<section id="import" class="padded">
    <a href="/admin/import_books" class="btn btn-primary">Import books</a>
</section>


<section id="new-book-form" class="padded">
    <h3>Filter books that are being borrowed for more than X days</h3>
    <form class="form-horizontal" method="POST" action='/admin/borrowed_books' >
        <div class="form-group">
            <label for="day" class="col-sm-1 control-label">Days:</label>
            <div class="col-sm-10">
                <input type="number" id="day" name="day" class="form-control" min=0 required/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-2">
                <button type="submit" name="submit" class="btn btn-primary">Filter</button>
            </div>
        </div>
    </form>
</section>


<section id="book-list" class="padded">
    <h3>Book list</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Author</th>
                <th>ISBN</th>
                <th>Borrowed</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getBooks() as $book): /** @var Book $book */?>
            <tr>
                <td><?= $book->getId()?></td>
                <td><?= $book->getTitle()?></td>
                <td><?= $book->getAuthor()?></td>
                <td><?= $book->getIsbn()?></td>
                <td><?= $book->isBorrowed() ? 'Yes' : 'No' ?></td>
                <td><a href="/admin/edit_book/<?=$book->getId()?>">Edit</a></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>



<?php require_once(__DIR__ . '/../../common/footer.phtml'); ?>

